version: '3'
services:
  redis:
    image: redis:5.0.5
    command: redis-server --requirepass redispass
    ports:
      - "6379:6379"
 
  postgres:
    image: postgres:11-alpine
    env_file:
      - ./cluster.env
    ports:
      - "5432:5432"
 
  flower:
      image: puckel-airflow-with-docker-inside    
      build: airflow/
      restart: always
      depends_on:
          - redis
      env_file:
      - ./cluster.env
      environment:
          - EXECUTOR=Celery
      ports:
          - "5555:5555"
      command: flower
